- hosts: MASTERS
  gather_facts: false
  become: true
  tasks:

    - name: kubectl start network pod
      raw: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
      args:
      executable: /bin/bash

    - name: kubectl start kubernetes dashboard 
      raw: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f "https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml"
      args:
      executable: /bin/bash
